-- Exercise 5.2: Assume the following code:
-- a = {}
-- a.a = a 
-- What would be the value of a.a.a.a? Is any a in that sequence somehow different from the others ?
-- Answer: Apparently it is all references to the same table.
-- Now, add the next line to the previous code:
-- a.a.a.a = 3
-- what would be the value of a.a.a.a now ?
-- answer: when you assign 3 to a.a.a.a, you are actually setting the field a in the table a to the value 3. This action breaks the self-reference because now a.a no longer refers to the table a; instead, it holds the value 3.
